<?php

namespace Database\Seeders;

use App\Models\Delivery;
use App\Models\Order;
use App\Models\User;
use Illuminate\Database\Seeder;

class DeliveriesSeeder extends Seeder
{
    public function run(): void
    {
        $orders = Order::where('pharmacy_id', 1)->get();
        $driver = User::where('role', 'pharmacist')->first();

        $deliveries = [
            [
                'order_index' => 0,
                'delivery_code' => 'DLV-0001',
                'customer_name' => 'Grace Hospital',
                'customer_phone' => '+255700000010',
                'delivery_address' => 'Sokoine Drive, Dar es Salaam',
                'delivery_fee' => 5000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(10)->addHours(2),
                'actual_arrival' => now()->subDays(10)->addHours(1),
            ],
            [
                'order_index' => 1,
                'delivery_code' => 'DLV-0002',
                'customer_name' => 'Alice Mwamba',
                'customer_phone' => '+255700000011',
                'delivery_address' => 'Mtaa wa Amani, Dar es Salaam',
                'delivery_fee' => 3000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(8)->addHours(2),
                'actual_arrival' => now()->subDays(8)->addHours(3),
            ],
            [
                'order_index' => 3,
                'delivery_code' => 'DLV-0003',
                'customer_name' => 'City Clinic',
                'customer_phone' => '+255700000013',
                'delivery_address' => 'Ohio Street, Dar es Salaam',
                'delivery_fee' => 5000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(5)->addHours(3),
                'actual_arrival' => now()->subDays(5)->addHours(2),
            ],
            [
                'order_index' => 8,
                'delivery_code' => 'DLV-0004',
                'customer_name' => 'City Clinic',
                'customer_phone' => '+255700000013',
                'delivery_address' => 'Ohio Street, Dar es Salaam',
                'delivery_fee' => 5000,
                'status' => 'in_transit',
                'estimated_arrival' => now()->addHours(1),
            ],
            [
                'order_index' => 9,
                'delivery_code' => 'DLV-0005',
                'customer_name' => 'Carol Banda',
                'customer_phone' => '+255700000014',
                'delivery_address' => 'Mikocheni, Dar es Salaam',
                'delivery_fee' => 3500,
                'status' => 'pending',
            ],
            [
                'order_index' => 2,
                'delivery_code' => 'DLV-0006',
                'customer_name' => 'Bob Phiri',
                'customer_phone' => '+255700000012',
                'delivery_address' => 'Bagamoyo Road, Dar es Salaam',
                'delivery_fee' => 4000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(9)->addHours(2),
                'actual_arrival' => now()->subDays(9)->addHours(1),
            ],
            [
                'order_index' => 4,
                'delivery_code' => 'DLV-0007',
                'customer_name' => 'Alice Mwamba',
                'customer_phone' => '+255700000011',
                'delivery_address' => 'Mtaa wa Amani, Dar es Salaam',
                'delivery_fee' => 3000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(7)->addHours(2),
                'actual_arrival' => now()->subDays(7)->addHours(2),
            ],
            [
                'order_index' => 5,
                'delivery_code' => 'DLV-0008',
                'customer_name' => 'Carol Banda',
                'customer_phone' => '+255700000014',
                'delivery_address' => 'Mikocheni, Dar es Salaam',
                'delivery_fee' => 3500,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(6)->addHours(3),
                'actual_arrival' => now()->subDays(6)->addHours(2),
            ],
            [
                'order_index' => 6,
                'delivery_code' => 'DLV-0009',
                'customer_name' => 'Bob Phiri',
                'customer_phone' => '+255700000012',
                'delivery_address' => 'Bagamoyo Road, Dar es Salaam',
                'delivery_fee' => 4000,
                'status' => 'failed',
                'estimated_arrival' => now()->subDays(4)->addHours(2),
                'actual_arrival' => null,
            ],
            [
                'order_index' => 7,
                'delivery_code' => 'DLV-0010',
                'customer_name' => 'Grace Hospital',
                'customer_phone' => '+255700000010',
                'delivery_address' => 'Sokoine Drive, Dar es Salaam',
                'delivery_fee' => 5000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(3)->addHours(2),
                'actual_arrival' => now()->subDays(3)->addHours(1),
            ],
            [
                'order_index' => 0,
                'delivery_code' => 'DLV-0011',
                'customer_name' => 'Mkulima Clinic',
                'customer_phone' => '+255700000015',
                'delivery_address' => 'Sinza, Dar es Salaam',
                'delivery_fee' => 4500,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(12)->addHours(2),
                'actual_arrival' => now()->subDays(12)->addHours(2),
            ],
            [
                'order_index' => 1,
                'delivery_code' => 'DLV-0012',
                'customer_name' => 'Tumaini Hospital',
                'customer_phone' => '+255700000016',
                'delivery_address' => 'Tandale, Dar es Salaam',
                'delivery_fee' => 5500,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(11)->addHours(3),
                'actual_arrival' => now()->subDays(11)->addHours(2),
            ],
            [
                'order_index' => 2,
                'delivery_code' => 'DLV-0013',
                'customer_name' => 'Neema Pharmacy',
                'customer_phone' => '+255700000017',
                'delivery_address' => 'Upanga, Dar es Salaam',
                'delivery_fee' => 4000,
                'status' => 'assigned',
                'estimated_arrival' => now()->addHours(3),
            ],
            [
                'order_index' => 3,
                'delivery_code' => 'DLV-0014',
                'customer_name' => 'Juhudi Health Centre',
                'customer_phone' => '+255700000018',
                'delivery_address' => 'Mwananyamala, Dar es Salaam',
                'delivery_fee' => 3500,
                'status' => 'picked_up',
                'estimated_arrival' => now()->addHours(1),
            ],
            [
                'order_index' => 4,
                'delivery_code' => 'DLV-0015',
                'customer_name' => 'Baraka Clinic',
                'customer_phone' => '+255700000019',
                'delivery_address' => 'Kigogo, Dar es Salaam',
                'delivery_fee' => 3000,
                'status' => 'in_transit',
                'estimated_arrival' => now()->addHours(2),
            ],
            [
                'order_index' => 5,
                'delivery_code' => 'DLV-0016',
                'customer_name' => 'Amani Dispensary',
                'customer_phone' => '+255700000021',
                'delivery_address' => 'Magomeni, Dar es Salaam',
                'delivery_fee' => 3500,
                'status' => 'pending',
            ],
            [
                'order_index' => 6,
                'delivery_code' => 'DLV-0017',
                'customer_name' => 'Bwawani Hospital',
                'customer_phone' => '+255700000022',
                'delivery_address' => 'Posta, Dar es Salaam',
                'delivery_fee' => 6000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(2)->addHours(2),
                'actual_arrival' => now()->subDays(2)->addHours(1),
            ],
            [
                'order_index' => 7,
                'delivery_code' => 'DLV-0018',
                'customer_name' => 'Mwangaza Clinic',
                'customer_phone' => '+255700000023',
                'delivery_address' => 'Kilwa Road, Dar es Salaam',
                'delivery_fee' => 5000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(1)->addHours(2),
                'actual_arrival' => now()->subDays(1)->addHours(1),
            ],
            [
                'order_index' => 8,
                'delivery_code' => 'DLV-0019',
                'customer_name' => 'Furaha Pharmacy',
                'customer_phone' => '+255700000024',
                'delivery_address' => 'Manzese, Dar es Salaam',
                'delivery_fee' => 3000,
                'status' => 'failed',
                'estimated_arrival' => now()->subDays(4)->addHours(2),
                'actual_arrival' => null,
            ],
            [
                'order_index' => 9,
                'delivery_code' => 'DLV-0020',
                'customer_name' => 'Hurry Hospital',
                'customer_phone' => '+255700000025',
                'delivery_address' => 'Tabata, Dar es Salaam',
                'delivery_fee' => 4500,
                'status' => 'pending',
            ],
            [
                'order_index' => 0,
                'delivery_code' => 'DLV-0021',
                'customer_name' => 'Mwananchi Health',
                'customer_phone' => '+255700000026',
                'delivery_address' => 'Buguruni, Dar es Salaam',
                'delivery_fee' => 3500,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(13)->addHours(2),
                'actual_arrival' => now()->subDays(13)->addHours(2),
            ],
            [
                'order_index' => 1,
                'delivery_code' => 'DLV-0022',
                'customer_name' => 'Ilala District Hospital',
                'customer_phone' => '+255700000027',
                'delivery_address' => 'Ilala, Dar es Salaam',
                'delivery_fee' => 5500,
                'status' => 'delivered',
                'estimated_arrival' => now()->subDays(14)->addHours(3),
                'actual_arrival' => now()->subDays(14)->addHours(2),
            ],
            [
                'order_index' => 2,
                'delivery_code' => 'DLV-0023',
                'customer_name' => 'Sabasaba Clinic',
                'customer_phone' => '+255700000028',
                'delivery_address' => 'Kariakoo, Dar es Salaam',
                'delivery_fee' => 2500,
                'status' => 'in_transit',
                'estimated_arrival' => now()->addHours(1),
            ],
            [
                'order_index' => 3,
                'delivery_code' => 'DLV-0024',
                'customer_name' => 'Uzima Dispensary',
                'customer_phone' => '+255700000029',
                'delivery_address' => 'Kinondoni, Dar es Salaam',
                'delivery_fee' => 4000,
                'status' => 'assigned',
                'estimated_arrival' => now()->addHours(4),
            ],
            [
                'order_index' => 4,
                'delivery_code' => 'DLV-0025',
                'customer_name' => 'Asha Pharmacy',
                'customer_phone' => '+255700000030',
                'delivery_address' => 'Kawe, Dar es Salaam',
                'delivery_fee' => 5000,
                'status' => 'picked_up',
                'estimated_arrival' => now()->addHours(2),
            ],
            [
                'order_index' => 5,
                'delivery_code' => 'DLV-0026',
                'customer_name' => 'Mbinga Hospital',
                'customer_phone' => '+255700000031',
                'delivery_address' => 'Mbagala, Dar es Salaam',
                'delivery_fee' => 4500,
                'status' => 'pending',
            ],
            [
                'order_index' => 6,
                'delivery_code' => 'DLV-0027',
                'customer_name' => 'Hema Health Centre',
                'customer_phone' => '+255700000032',
                'delivery_address' => 'Vingunguti, Dar es Salaam',
                'delivery_fee' => 3000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subHours(18)->addHours(2),
                'actual_arrival' => now()->subHours(18)->addHours(1),
            ],
            [
                'order_index' => 7,
                'delivery_code' => 'DLV-0028',
                'customer_name' => 'Rahima Hospital',
                'customer_phone' => '+255700000033',
                'delivery_address' => 'Oysterbay, Dar es Salaam',
                'delivery_fee' => 6000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subHours(12)->addHours(2),
                'actual_arrival' => now()->subHours(12)->addHours(1),
            ],
            [
                'order_index' => 8,
                'delivery_code' => 'DLV-0029',
                'customer_name' => 'Mama Ntilie Clinic',
                'customer_phone' => '+255700000034',
                'delivery_address' => 'Mtoni, Dar es Salaam',
                'delivery_fee' => 3500,
                'status' => 'in_transit',
                'estimated_arrival' => now()->addHours(1),
            ],
            [
                'order_index' => 9,
                'delivery_code' => 'DLV-0030',
                'customer_name' => 'Zenathi Pharmacy',
                'customer_phone' => '+255700000035',
                'delivery_address' => 'Mbezi, Dar es Salaam',
                'delivery_fee' => 5000,
                'status' => 'pending',
            ],
            [
                'order_index' => 0,
                'delivery_code' => 'DLV-0031',
                'customer_name' => 'Tandale Dispensary',
                'customer_phone' => '+255700000036',
                'delivery_address' => 'Tandale, Dar es Salaam',
                'delivery_fee' => 3000,
                'status' => 'delivered',
                'estimated_arrival' => now()->subHours(8)->addHours(2),
                'actual_arrival' => now()->subHours(8)->addHours(1),
            ],
            [
                'order_index' => 1,
                'delivery_code' => 'DLV-0032',
                'customer_name' => 'Kigogo Health Centre',
                'customer_phone' => '+255700000037',
                'delivery_address' => 'Kigogo, Dar es Salaam',
                'delivery_fee' => 3500,
                'status' => 'failed',
                'estimated_arrival' => now()->subHours(6)->addHours(2),
                'actual_arrival' => null,
            ],
            [
                'order_index' => 2,
                'delivery_code' => 'DLV-0033',
                'customer_name' => 'Sinza Pharmacy',
                'customer_phone' => '+255700000038',
                'delivery_address' => 'Sinza, Dar es Salaam',
                'delivery_fee' => 4000,
                'status' => 'assigned',
                'estimated_arrival' => now()->addHours(3),
            ],
            [
                'order_index' => 3,
                'delivery_code' => 'DLV-0034',
                'customer_name' => 'Magomeni Hospital',
                'customer_phone' => '+255700000039',
                'delivery_address' => 'Magomeni, Dar es Salaam',
                'delivery_fee' => 4500,
                'status' => 'pending',
            ],
            [
                'order_index' => 4,
                'delivery_code' => 'DLV-0035',
                'customer_name' => 'Upanga Clinic',
                'customer_phone' => '+255700000040',
                'delivery_address' => 'Upanga, Dar es Salaam',
                'delivery_fee' => 5000,
                'status' => 'in_transit',
                'estimated_arrival' => now()->addHours(2),
            ],
        ];

        foreach ($deliveries as $delivery) {
            $order = $orders[$delivery['order_index']] ?? $orders->first();
            if (!$order) continue;

            Delivery::create([
                'pharmacy_id' => 1,
                'order_id' => $order->id,
                'delivery_code' => $delivery['delivery_code'],
                'customer_name' => $delivery['customer_name'],
                'customer_phone' => $delivery['customer_phone'],
                'delivery_address' => $delivery['delivery_address'],
                'delivery_fee' => $delivery['delivery_fee'],
                'status' => $delivery['status'],
                'assigned_to' => $driver?->id,
                'estimated_arrival' => $delivery['estimated_arrival'] ?? null,
                'actual_arrival' => $delivery['actual_arrival'] ?? null,
            ]);
        }
    }
}
