<?php

namespace Database\Seeders;

use App\Models\Pharmacy;
use App\Models\Subscription;
use Illuminate\Database\Seeder;

class SubscriptionsSeeder extends Seeder
{
    public function run(): void
    {
        $pharmacies = Pharmacy::all();

        $plans = [
            ['plan' => 'trial', 'amount' => 0, 'status' => 'active'],
            ['plan' => 'basic', 'amount' => 49000, 'status' => 'active'],
            ['plan' => 'pro', 'amount' => 132300, 'status' => 'active'],
            ['plan' => 'enterprise', 'amount' => 441000, 'status' => 'active'],
        ];

        foreach ($pharmacies as $index => $pharmacy) {
            $plan = $plans[$index % count($plans)];

            Subscription::create([
                'pharmacy_id' => $pharmacy->id,
                'plan' => $plan['plan'],
                'amount' => $plan['amount'],
                'payment_method' => $plan['amount'] > 0 ? 'bank' : null,
                'transaction_id' => $plan['amount'] > 0 ? 'TXN-' . strtoupper(uniqid()) : null,
                'status' => $plan['status'],
                'start_date' => now()->subMonths(2),
                'end_date' => $plan['plan'] === 'trial' ? now()->addDays(7) : now()->addMonths(12),
            ]);
        }

        $extraSubscriptions = [
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-MOB-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(25),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-BNK-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(20),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'enterprise',
                'amount' => 441000,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-ENT-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(18),
                'end_date' => now()->addYear(),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'trial',
                'amount' => 0,
                'payment_method' => null,
                'transaction_id' => null,
                'status' => 'expired',
                'start_date' => now()->subDays(30),
                'end_date' => now()->subDays(23),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-MOB-' . strtoupper(uniqid()),
                'status' => 'cancelled',
                'start_date' => now()->subDays(28),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR-' . strtoupper(uniqid()),
                'status' => 'suspended',
                'start_date' => now()->subDays(15),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-B1-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(14),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'enterprise',
                'amount' => 441000,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-EN2-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(12),
                'end_date' => now()->addYear(),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR2-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(10),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-B2-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(9),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'trial',
                'amount' => 0,
                'payment_method' => null,
                'transaction_id' => null,
                'status' => 'active',
                'start_date' => now()->subDays(8),
                'end_date' => now()->addDays(7),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR3-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(7),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'enterprise',
                'amount' => 441000,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-EN3-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(6),
                'end_date' => now()->addYear(),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-B3-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(5),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR4-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(4),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-B4-' . strtoupper(uniqid()),
                'status' => 'expired',
                'start_date' => now()->subDays(22),
                'end_date' => now()->subDays(8),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'enterprise',
                'amount' => 441000,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-EN4-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(3),
                'end_date' => now()->addYear(),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'trial',
                'amount' => 0,
                'payment_method' => null,
                'transaction_id' => null,
                'status' => 'active',
                'start_date' => now()->subDays(2),
                'end_date' => now()->addDays(7),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR5-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(1),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-B5-' . strtoupper(uniqid()),
                'status' => 'pending',
                'start_date' => now(),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'enterprise',
                'amount' => 441000,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-EN5-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(16),
                'end_date' => now()->addYear(),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR6-' . strtoupper(uniqid()),
                'status' => 'cancelled',
                'start_date' => now()->subDays(24),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-B6-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(11),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'enterprise',
                'amount' => 441000,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-EN6-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(13),
                'end_date' => now()->addYear(),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR7-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(17),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-B7-' . strtoupper(uniqid()),
                'status' => 'suspended',
                'start_date' => now()->subDays(19),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'enterprise',
                'amount' => 441000,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-EN7-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(21),
                'end_date' => now()->addYear(),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR8-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(23),
                'end_date' => now()->addMonths(12),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'basic',
                'amount' => 49000,
                'payment_method' => 'mobile',
                'transaction_id' => 'TXN-B8-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(26),
                'end_date' => now()->addMonths(1),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'enterprise',
                'amount' => 441000,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-EN8-' . strtoupper(uniqid()),
                'status' => 'active',
                'start_date' => now()->subDays(27),
                'end_date' => now()->addYear(),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'trial',
                'amount' => 0,
                'payment_method' => null,
                'transaction_id' => null,
                'status' => 'expired',
                'start_date' => now()->subDays(29),
                'end_date' => now()->subDays(22),
            ],
            [
                'pharmacy_id' => 1,
                'plan' => 'pro',
                'amount' => 132300,
                'payment_method' => 'bank',
                'transaction_id' => 'TXN-PR9-' . strtoupper(uniqid()),
                'status' => 'pending',
                'start_date' => now(),
                'end_date' => now()->addMonths(12),
            ],
        ];

        foreach ($extraSubscriptions as $sub) {
            Subscription::create($sub);
        }
    }
}
